import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { GoHome } from "react-icons/go";
import { FiSearch } from "react-icons/fi";
import { TbSquareRoundedPlus } from "react-icons/tb";
import { PiVideo } from "react-icons/pi";
import Link from "next/link";
import { PostsProvider } from "./post-context";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Minegram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <PostsProvider>
            {children}

            {/* Bottom Nav */}
            <nav className="fixed bottom-0 left-0 w-full bg-white border-t flex justify-around items-center py-2 shadow-lg">
              <Link href="/" className="flex flex-col items-center text-gray-700 hover:text-black">
                <GoHome size={24} />
              </Link>
              <Link href="/search" className="flex flex-col items-center text-gray-700 hover:text-black">
                <FiSearch size={24} />
              </Link>
              <button className="flex flex-col items-center text-gray-700 hover:text-black">
                <TbSquareRoundedPlus size={24} />
              </button>
              <button className="flex flex-col items-center text-gray-700 hover:text-black">
                <PiVideo size={24} />
              </button>
              <Link href="/profile" className="flex flex-col items-center text-gray-700 hover:text-black">
                User
              </Link>
            </nav>
          </PostsProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
